# Settings
baseurl = ""
languageCode = "en-us"
title = "Trishti Gupta"
theme = "autophugo"
disableKinds = ["taxonomy", "term"]
#[taxonomies]
#    tag = "tags"
#    category = "categories"

[services]
    [services.googleAnalytics]
        #ID = 'G-MEASUREMENT_ID'

[params]
    # Meta
    description = "Trishti Gupta"
    keywords = "photoblog, Trishti"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    #thumb_quality = 50
    #full_width = 960
    #full_quality = 90
    #column_count = 2
    #breadcrumb_use_title = false
    #filename_as_phototitle = false
    images_downloadable = false
    #images_downloadable_use_orig = false
    #taxonomies_links = false

    [params.author]
    name = "Trishti Gupta"
    email = "trishtigupta2002@gmail.com"

    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"

    # Footer panel

    [params.footer.paragraph]
    headline = "Trishti Gupta"
    text = " I’m Trishti Gupta, an artist, illustrator, and creative professional with a passion for bringing ideas to life through art. I blend traditional techniques with modern design to create unique, captivating pieces that tell compelling stories. Whether through illustration, digital art, or design, I love crafting visuals that inspire and connect with others. Join me in exploring my creative journey and discover how my work transforms imagination into visual masterpieces."

    [params.footer.social]
    headline = "Follow me"

    [[params.footer.social.links]]
    label = "Twitter"
    url = "#"
    icon = "fa-twitter"

    [[params.footer.social.links]]
    label = "Facebook"
    url = "#"
    icon = "fa-facebook"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "#"
    icon = "fa-instagram"

    [[params.footer.social.links]]
    label = "Github"
    url = "#"
    icon = "fa-github"

    [[params.footer.social.links]]
    label = "LinkedIn"
    url = "#"
    icon = "fa-linkedin"

    # Contact form

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your integration endpoint address under 'formspreeID' below
    # - create a formspree account and a simple form 
    # - then get the integration endpoint generated to you form
    # - you're done. Happy mailing!

    [params.footer.contact]
    hide = true # Set this to true if you don't want to have a contact form on your site
    formspreeID = "myuniqueID" # Getting value from Formspree integration endpoint (eg. https://formspree.io/f/myuniqueID)
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"

    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"

    # Copyright
    [params.footer.copyright]
    name = "Your name"
