baseURL = "https://trishtigupta.github.io/"
languageCode = "en-us"
title = "Trishti Gupta"

publishDir = "docs"

disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 18

[params]
  description = "A minimalist portfolio showcasing artworks in a scrolling gallery."
  
  [params.colors]
  bg = "#ffffff"           # white background
  fg = "#111111"            # keep strong contrast for text
  muted = "#6b7280"
  tileBg = "#ffffff"
  accent = "#ff9f75"        # accent from your palette
  labelBg = "rgba(255,159,117,0.45)"  # subtle orange-tinted overlay
  labelFg = "#ffffff"
  divider = "#e5e7eb"
  shadow = "rgba(0,0,0,0.06)"
  headerBg = "rgba(255,159,117,0.15)" # orange-tinted header when scrolled
  headerBorder = "#ff9f75"

[menu]
  [[menu.main]]
    name = "Recent Work"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
  weight = 20
