name: Build Test
on:
    schedule:
      - cron: "29 1 1 * *"
    workflow_dispatch:
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Install Hugo
            run: sudo snap install hugo
          - name: Checkout Repo
            uses: actions/checkout@v4
          - name: Build Pages
            run: make
